# NumPy Examples Notebook

Below is a general outline of a Jupyter Notebook (`examples.ipynb`) showcasing various NumPy features.  
You can split these sections into multiple cells in your Jupyter environment.

---

## 1. Creating Arrays and Checking Attributes

In [3]:
    import numpy as np

    # 1D array
    arr_1d = np.array([10, 20, 30, 40])
    print("arr_1d:", arr_1d)
    print("Shape:", arr_1d.shape)
    print("Size:", arr_1d.size)
    print("ndim:", arr_1d.ndim)

arr_1d: [10 20 30 40]
Shape: (4,)
Size: 4
ndim: 1


---

## 2. Random Matrix and Basic Statistics

In [5]:
    mat_random = np.random.randint(1, 10, (3, 3))
    print("Random 3x3 Matrix:\n", mat_random)
    print("Mean:", mat_random.mean())
    print("Max:", mat_random.max())
    print("Argmax (index of max value):", mat_random.argmax())

Random 3x3 Matrix:
 [[5 7 8]
 [1 4 8]
 [2 6 2]]
Mean: 4.777777777777778
Max: 8
Argmax (index of max value): 2


---

## 3. Indexing and Slicing

In [6]:
    mat = np.array([
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]
    ])
    print("mat[1, 1] =", mat[1, 1])  # 21

    sub_mat = mat[0:2, 1:]
    print("Sliced sub_mat:\n", sub_mat)

mat[1, 1] = 21
Sliced sub_mat:
 [[11 12]
 [21 22]]


---

## 4. Reshape and Flatten

In [8]:
    arr_12 = np.arange(12)  # [0,1,2,...,11]
    mat_3x4 = arr_12.reshape((3, 4))
    print("3x4 matrix:\n", mat_3x4)

    flat = mat_3x4.flatten()
    print("Flattened:", flat)

3x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


---

## 5. Arithmetic Operations

In [10]:
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("arr1 + arr2 =", arr1 + arr2)
    print("arr1 * arr2 =", arr1 * arr2)

    # Matrix multiplication
    A = np.array([
        [1, 2],
        [3, 4]
    ])
    B = np.array([
        [5, 6],
        [7, 8]
    ])
    C = A.dot(B)
    print("Matrix Product:\n", C)

arr1 + arr2 = [5 7 9]
arr1 * arr2 = [ 4 10 18]
Matrix Product:
 [[19 22]
 [43 50]]
